### ISSUE TITLE
Logging out from Evrima RCON wanted

### ISSUE THREAD

**Issue by BechmannCom** [modernham/The-Isle-Evrima-Server-Tools#2]
After authentication the rcon stays authenticated for all subsequest connections until server is rebooted. Do you know how to logout again to avoid any security issues?

Server log on first login attempt: "LogTemp: Warning: New RCON Connection Authenticated!"
Server log on second login attempt: "LogTemp: Warning: RCON Connection Already Authenticated!" (this even if you specify empty or wrong password)

**Comment by modernham** [comment]
The Development team have not implemented a logout mechanism so it is not yet possible to de-authenticate.
