### ISSUE TITLE
Has anyone figured out /grow command via RCON?

### ISSUE THREAD

**Issue by reddiedev** [modernham/The-Isle-Evrima-Server-Tools#4]
Am trying to execute a /grow command via the RCON, but it seems it is not available yet

**Comment by modernham** [comment]
Yes, you are correct. The grow command is not available with RCON yet. This is not a RCON client issue, but a lack of support for the command from the RCON server within the game itself.
You will want to talk to the devs about this. 

In the future, github issues are typically used for bugs or features requests pertaining to the repository itself. 

You can find the documentation for RCON here https://docs.google.com/document/u/0/d/1JI_qVdKIZrqcVTY2Tqnm1T_Ws3_1r5nINGxfprbWw7w/mobilebasic?pli=1#heading=h.p9tfb89b07jd
